name: CI

on:
  push:
    branches:
      - master

jobs:
  build-test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Configurar ambiente Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # ajuste conforme a versão do Node.js que você está usando

    - name: Instalar dependências
      run: npm install

    - name: Build do projeto
      run: npm run build
    - name: Rodar testes unitários
      run: npm run test
      env:
        CI: true

  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Setup da action do Docker
      uses: docker/setup-buildx-action@v2

    - name: Login no Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Checkout do código 
      uses: actions/checkout@v2

    - name: Build e push da imagem Docker
      uses: docker/build-push-action@v5
      with:
        context: ./
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/energia-scan-web:latest